#======================================#
#========== Project settings ==========#
#======================================#

# 产品或项目名称、软件开发公司名称
productName: JeeSite 测试环境
companyName: ThinkGem

# 产品版本、版权年份
productVersion: V4.1
copyrightYear: 2020

#是否演示模式
demoMode: false

#======================================#
#========== Server settings ===========#
#======================================#

server:

  port: 8980
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

  # 将请求协议转换为 https
  schemeHttps: false

#======================================#
#========== Database sttings ==========#
#======================================#
# 数据库连接
jdbc: 
  
  # Mysql 数据库配置
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://mysql_ip:mysql_port/jeesite?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
  username: mysql_user
  password: mysql_pwd
  testSql: SELECT 1

# MyBatis 相关
mybatis:

  # Mapper文件刷新线程
  mapper:
    refresh:
      enabled: false
      
# 文件相关
file:

  # 文件上传根路径，设置路径中不允许包含“userfiles”，在指定目录中系统会自动创建userfiles目录，如果不设置默认为contextPath路径
  baseDir: /root/jeesite
  
